### ISSUE TITLE
Issue when running ffi-libfreenect in Linux

### ISSUE THREAD

**Issue by jgrunzweig** [jgrunzweig/ffi-libfreenect#1]
The following error is generated when you run ffi-libfreenect in Linux:

Hi Josh,

I was wondering if you could lend a hand. I'm getting the following error when attempting to run any of the examples:

/usr/lib/ruby/1.8/ffi/library.rb:113:in `attach_function': Function 'freenect_sync_get_video' not found in [libfreenect.so, libfreenect_sync.so](FFI::NotFoundError)

from /home/miguel/Kinect/ruby/openkinect/wrappers/ruby/ffi-libfreenect/lib/ffi/freenect.rb:164
from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
from /home/miguel/Kinect/ruby/openkinect/wrappers/ruby/ffi-libfreenect/lib/freenect.rb:4
from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
from record.rb:18

Thanks to Miguel for the heads up!

**Comment by emonti** [comment]
This is most likely because an older version of the libfreenect library is included with the linux package in use. We have made the 'sync' library bindings conditional upon availability. A warning will be issued if an older version of the library is installed, but the core library bindings should still work.

**Comment by jgrunzweig** [comment]
Fix appears to have solved the issue. Will confirm tonight when I get my hands on my Kinect.

**Comment by emonti** [comment]
Can you confirm this worked? I'd like to close the issue.

cheers

**Comment by jgrunzweig** [comment]
The guy who reported it said he was still having problems. I'm going to see if I can't troubleshoot this tonight.

-Josh

---

miguel@satellite:~/Kinect/ffi-libfreenect/examples$ ruby record.rb
/usr/lib/ruby/gems/1.8/gems/ffi-1.0.4/lib/ffi/library.rb:75:in `ffi_lib': Could not open library 'freenect': freenect: cannot open shared object file: No such file or directory. Could not open library 'libfreenect.so': libfreenect.so: cannot open shared object file: No such file or directory (LoadError)

from /usr/lib/ruby/gems/1.8/gems/ffi-1.0.4/lib/ffi/library.rb:54:in `map'
from /usr/lib/ruby/gems/1.8/gems/ffi-1.0.4/lib/ffi/library.rb:54:in`ffi_lib'
from /home/miguel/Kinect/ffi-libfreenect/lib/ffi/freenect.rb:11
from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in `gem_original_require'
from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in`require'
from /home/miguel/Kinect/ffi-libfreenect/lib/freenect.rb:4
from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in `gem_original_require'
from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:29:in`require'
from record.rb:18
I have the following gems:
ffi (1.0.4)
ffi-libfreenect (0.1.1)
